### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Nosta54** [GreyHak/dsp-infinite-resource-nodes#1]
Hello !
I've installed the mod, bur ther rises an error launching the program (mod not working)
The error is :

[Message:   BepInEx] BepInEx 5.4.5.0 - DSPGAME
[Info   :   BepInEx] Running under Unity v2018.4.12.5889476
[Info   :   BepInEx] CLR runtime version: 2.0.50727.1433
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [DSPInfiniteResourceNodes 1.0.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   BepInEx] Patching [Assembly-CSharp] with [DSPInfiniteResourceNodes.DSPInfiniteResourceNodes]
[Info   :DSP Infinite Resource Nodes] Infinite resources patch applied for miners.
[Info   :DSP Infinite Resource Nodes] IL_0532: ldloc.s V_24
[Info   :DSP Infinite Resource Nodes] IL_05e1: ldloc.s V_24
[Info   :DSP Infinite Resource Nodes] IL_0603: ldloc.s V_24
[Error  :DSP Infinite Resource Nodes] ERROR: The Dyson Sphere Program appears to have been updated.  The Infinite Resource Nodes mod needs to be updated.  Until then Icarus will consume node resources.
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete

Result is :
Ore ressources running out, saw this on : stonec, copper

Are u able to send a helpful answer or correct this issue ?

Best regards and thank's for help
Norbert

**Comment by GreyHak** [comment]
@Nosta54 Thank you for the report.  I'll get on it right now.

**Comment by GreyHak** [comment]
@Nosta54 Looks like this issue is only impacting Icarus.  The miners aren't consuming resources.  I'll have this fixed today.  I'll implement a more robust solution that is less prone to game updates.

**Comment by GreyHak** [comment]
@Nosta54 Issue fixed in release v1.1.0.  This fix should also be less susceptible to breaking when the game updates in the future.  I've also added something to make it easier for me to monitor for breakages while I'm in a mode where I want to consume resources so I can find out about this type of issue sooner.  Thank you again for bringing this to my attention.

**Comment by Nosta54** [comment]
Hello,
I,ve updated to the new version.


I thank you very much for correcting this 'bug ( *gg )

thanks for the very nice work.
have a nice weekend

greetings from
Germany

Norbert




 
 
 
-----Ursprüngliche Mitteilung-----
Von: GreyHak ***@***.***>
An: GreyHak/dsp-infinite-resource-nodes ***@***.***>
Cc: Nosta54 ***@***.***>; Mention ***@***.***>
Verschickt: Fr, 19. Mrz 2021 21:16
Betreff: Re: [GreyHak/dsp-infinite-resource-nodes] Bug Report (#1)

@Nosta54 Issue fixed in release v1.1.0. This fix should also be less susceptible to breaking when the game updates in the future. I've also added something to make it easier for me to monitor for breakages while I'm in a mode where I want to consume resources so I can find out about this type of issue sooner. Thank you again for bringing this to my attention.—
