### ISSUE TITLE
Seems to no longer work with last update

### ISSUE THREAD

**Issue by pegnunez** [GreyHak/dsp-infinite-resource-nodes#2]
So I was having a lot of fun with my particular heavily loaded mod profile, including this one. However, after starting a new playthorugh after last base game update, I notice this time around resource nodes are depleting. Any idea on what might be causing this?

**Comment by GreyHak** [comment]
Thank you for the report @pegnunez .  The update impacted only Icarus' mining, not the miner machines.  It has been fixed in release v1.1.1.

**Comment by Davimimus** [comment]
Hi, please forgive me for intervening here I did not find any other way to contact @pegnunez. Do you have any discord account or preferd place to discuss about the mods you've published on SMM ?
