### ISSUE TITLE
With unlimited resources disabled still have resources not going down.

### ISSUE THREAD

**Issue by Peacem8ker** [GreyHak/dsp-infinite-resource-nodes#5]
I have the mod configured so that oil is unlimited and all other resources are limited.   All of them are unlimited tried reinstalling.  It worked correctly maybe a week ago all the sudden stopped working properly.

**Comment by GreyHak** [comment]
@Peacem8ker The game update 2 weeks ago broke the mod.  The update from 2 weeks ago, v1.2.2, will have fixed it.  If you experience any more issues with the new version, please let me know.
