### ISSUE TITLE
Expand mod to oil (via option)

### ISSUE THREAD

**Issue by L1iMa** [GreyHak/dsp-infinite-resource-nodes#6]
Is it possible to expand this mod to oil too? Perhaps via an option to enable or disable. Would be great.
Thank you.

**Comment by GreyHak** [comment]
@L1iMa The mod already works for oil. Are you having trouble?

**Comment by L1iMa** [comment]
Oh, don't mind, sorry.

I only read the normal description and did oversee the patchnotes. Thanks for the reply.

No problems. ;)
