### ISSUE TITLE
Mod Stopped Working With patch 0.9.26.13026

### ISSUE THREAD

**Issue by M2262** [GreyHak/dsp-infinite-resource-nodes#7]
Hi there, not sure if the mod is still being worked on, but I thought I'd pass along it stopped working for me with the latest 0.9.26.13026 patch.

Thanks

**Comment by GreyHak** [comment]
Issue confirmed, impacting miners, oil extractors and Icarus.  Thank you for the report @M2262

**Comment by GreyHak** [comment]
@M2262  Fixed in  v1.2.3

**Comment by M2262** [comment]
Thanks for the Fix!
